### ISSUE TITLE
Add citation.cff

### ISSUE THREAD

**Issue by schroedtert** [PedestrianDynamics/pedpy#17]
Who needs to be referenced in the citation file?

**Comment by schroedtert** [comment]
```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: LAST_NAME
    given-names: FIRST_NAME
    orcid: https://orcid.org/ORCID
title: "Pedestrian trajectory analyzer"
version: VERSION
doi: XDOIX
date-released: YYYY-MM-DD
```
